FROM golang:1.19-alpine3.15 AS builder

ADD . /app
WORKDIR /app

RUN go mod download \
    && go build -o /build/server ./cmd/swagger/docs.go

FROM alpine:3.15
EXPOSE 80
COPY --from=builder /build/ /
CMD ["/server"]