services:
  app-base:
    build:
      dockerfile: 'Dockerfile.dev'
    expose:
      - 80
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - database
      - app

  app:
    extends:
      service: app-base
    ports:
      - 8080:80

  app-debug:
    extends:
      service: app-base
    command: [ "/bin/ash", "/app/build-and-debug.sh" ]
    ports:
      - 8082:80
      - 2345:2345

  docs:
    build:
      dockerfile: 'Dockerfile.docs'
    ports:
      - 8001:80
    networks:
      - app

  db:
    image: 'postgres:12-alpine3.15'
    expose:
      - 5423
    ports:
      - 5432:5432
    env_file:
      - .env.db
    networks:
      - database

  migrate:
    image: migrate/migrate:latest
    volumes:
      - ./migrations:/migrations
    depends_on:
      - db
    networks:
      - database
    command: [ "-path", "/migrations", "-database", "${DB_DSN}?sslmode=disable", "up" ]
    deploy:
      replicas: 0

  rollback:
    extends:
      service: migrate
    command: [ "-path", "/migrations", "-database", "${DB_DSN}?sslmode=disable", "down", "1" ]

  test:
    build:
      dockerfile: 'Dockerfile.dev'
    env_file:
      - .env.tests
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - tests-database
    command: [ "./run-tests.sh" ]

  tests-db:
    image: 'postgres:12-alpine3.15'
    expose:
      - 5432
    ports:
      - 15432:5432
    networks:
      - tests-database
    env_file:
      - .env.tests

volumes:
  db_data:

networks:
  app:
    driver: bridge
  database:
    driver: bridge
  tests-database:
    driver: bridge