// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/burenotti/rtu-it-lab-recruit/model"
	mock "github.com/stretchr/testify/mock"
)

// CodeDelivery is an autogenerated mock type for the CodeDelivery type
type CodeDelivery struct {
	mock.Mock
}

// SendCode provides a mock function with given fields: ctx, user, code
func (_m *CodeDelivery) SendCode(ctx context.Context, user *model.User, code string) error {
	ret := _m.Called(ctx, user, code)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User, string) error); ok {
		r0 = rf(ctx, user, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewCodeDelivery interface {
	mock.TestingT
	Cleanup(func())
}

// NewCodeDelivery creates a new instance of CodeDelivery. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCodeDelivery(t mockConstructorTestingTNewCodeDelivery) *CodeDelivery {
	mock := &CodeDelivery{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
